### ISSUE TITLE
Text3d ignores fonts

### ISSUE THREAD

**Issue by madhephaestus** [miho/JCSG#30]
Using  public Text3d(String text, String fontName, double fontSize, double depth)  and Font names:

"Times New Roman"
"Arial" 
"Helvetica"

All produce the same result. 

(This is cool feature to finally have, thank you!)

**Comment by madhephaestus** [comment]
GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
String [] fonts = ge.getAvailableFontFamilyNames();

Should be consulted for a list of availible fonts on a given system. If the font is missing form the list, maybe an error? Or at least a warning message?

**Comment by miho** [comment]
Your proposal uses the AWT/Swing APIs. We use FXyz which uses JavaFX for font rendering. `ge.getAvailableFontFamilyNames()` does not necessarily return the correct fonts since it does not know about custom fonts that might have been added to JavaFX.

If you need more support here, you should probably talk to the FXyz developers.
